version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "minify"
    schedule:
      interval: "monthly"
    groups:
      webdriverio:
        patterns:
          - '@wdio/*'
      babel:
        patterns:
          - '@babel/*'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "00:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: gh-actions
