name: Desktop
on:
  push:
    branches:
      - develop
      - '!dependabot/**'
  pull_request_target:
    types: [opened]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up node env
      uses: actions/setup-node@v4
      with:
        node-version: current
        cache: 'npm'
    - name: Install dependencies
      run: npm i && npm i --save-dev jsdoc
    - name: Set file perms on dev script
      if: ${{ !startsWith(runner.os, 'windows') }}
      run: chmod +x ./demo/clean
    - name: Build docs
      if: ${{ !startsWith(runner.os, 'windows') }}
      run: npm test
    - name: Build docs on Windows
      if: ${{ startsWith(runner.os, 'windows') }}
      run: npm run test:win
      shell: cmd
    - name: Upload static content
      if: ${{ startsWith(runner.os, 'linux') }}
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: './demo/output'
        retention-days: 1
        if-no-files-found: error

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up node env
      uses: actions/setup-node@v4
      with:
        node-version: current
        cache: 'npm'
    - name: Install dependencies
      run: npm i --omit=optional
    - name: Fetch static content
      uses: actions/download-artifact@v4
      with:
        path: ${{ github.workspace }}/demo/output
        merge-multiple: true
    - name: Set up BrowserStack env
      uses: clean-jsdoc/github-actions/setup-env@963f81eba6d574e37a9955fb27c6524695807f44
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    - name: Start BrowserStackLocal Tunnel
      uses: clean-jsdoc/github-actions/setup-local@963f81eba6d574e37a9955fb27c6524695807f44
      with:
        local-testing: start
        local-logging-level: false
        local-identifier: random
    - name: Run Selenium tests
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        PORT: 8099
      run: |
        npm run bs
        npm run bs:safari
    - name: Stop BrowserStackLocal
      uses: clean-jsdoc/github-actions/setup-local@963f81eba6d574e37a9955fb27c6524695807f44
      with:
        local-testing: stop
