name: Package
on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: write
      pages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up node env
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm i && npm i --save-dev jsdoc
    - name: Set file perms on dev script
      if: ${{ !startsWith(runner.os, 'windows') }}
      run: chmod +x ./demo/clean
    - name: Build docs with custom options
      if: ${{ !startsWith(runner.os, 'windows') }}
      run: npm test
    - name: Build docs on Windows
      if: ${{ startsWith(runner.os, 'windows') }}
      run: npm run test:win
      shell: cmd

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up node env
      uses: actions/setup-node@v4
      with:
        node-version: current
        registry-url: https://npm.pkg.github.com/
        cache: 'npm'
    - name: Publish to GH Packages
      run: |-
       npm ci
       npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
